<Project>
  <PropertyGroup>
    <KalynaSigningCertificateThumbprint>20ADC827C30C82C426D98318AB174030E7E168BA</KalynaSigningCertificateThumbprint>
    <KalynaExpectedSignerSha256>0F5192D845FF3805AF93AF7C3B507AFBA4FDC677BF53389DECA430E5127608FD</KalynaExpectedSignerSha256>
    <KalynaExpectedSignerSha3_512>5F42FE2F7BE777F5C0B3E7A589298DC21B9985304670415636C853E5B820B9797D3CF7370FA2469F3D5C7BB61096AED7D07C3443BC70A47A67F832B12D6F1E2D</KalynaExpectedSignerSha3_512>
    <KalynaExpectedSignerSkein1024>FA4DBD013DFAB615825D1B962B10414E4F74F39BEA92227740651BF3CC380C0B16755A988BB3518684982F4B725CAF4F1A869856136D7A5D19A1E198EFA4E22B05C93BAE3736E235F33931F469198B03F7A217EC1534ADB96E0B66EC30504F17458309A4C891B8FD616B00CFE583AA40E9C0F21B36240DA4DF6D4DEF1985DA57</KalynaExpectedSignerSkein1024>
    <KalynaExpectedMldsa87Sha256>2F4BB3FF9C087F2726BC5CABA1E3A10E834D7AE06B79415CD1E5875C89FE4FC1</KalynaExpectedMldsa87Sha256>
    <KalynaExpectedMldsa87Sha3_512>2EB20E4704B2172DB8E6DE292F9ACE87F4A30ECAD600E32D8BF00186A030745F583B80F3D329E1FF437B71DF57DA116266C6AEBAD279DC62E0175B577D64F497</KalynaExpectedMldsa87Sha3_512>
    <KalynaExpectedMldsa87Skein1024>528F7587887D4BDC3EF332E8866411498C0B60E63FD58846F284EC6576FDAA1B83A2398703137748F9F63556EDBCD1F0F1039687114148B97081D4D5C4AFE2DAF94B1E65D7800BFC6E6A84E74579548583DB953DA4E2126C89E9BB79046143D9E3D5B023E363348887637F889E3054EF4001749FB87BB85D40A42FE77A3E108F</KalynaExpectedMldsa87Skein1024>
  </PropertyGroup>
</Project>
